services:
  db:
    image: postgres:15-alpine
    container_name: local_postgres
    restart: always
    environment:
      # Define your credentials here
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=api_db
    ports:
      - "5454:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

volumes:
  postgres_local_data: